---
title: Rescuing data from a pdf
author: Helen Graham
date: '2019-03-23'
slug: pdf-scraping
categories:
  - R
tags:
  - tidyverse
  - pdftools
image: "img/jail-kittens.jpg"
description: "What to do when that data you want is trapped in a pdf"
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<p>I’ve had the unfortunate task recently of having to liberate some
data from pdfs; all part of the ‘Sexiest Job In The World’(TM).
Fortunately after some blundering about
I’ve managed to get a decent result, and I thought I’d write up the process because it’s no
doubt something I’m going to have to do again, and in case anyone else finds it useful.</p>
<p>The <code>pdftools</code> package has been around for a while, allowing you to extract data line by
line from a pdf. However, a relatively new feature (launched late last year) is the
<code>pdf_data()</code> function, which
tells you the position on the page of every word you extract. This is particularly useful if
you are trying to extract a table and can’t rely on inferring delimiters from whitespace.</p>
<p>The example I’m using here is not the pdf I was scraping for work, because that one is
extremely long and boring (unless you are <em>fascinated</em> by which types of colouring you
are allowed to feed to ornamental fish, or which gut flora stabilisers are permitted for
weaned piglets). Instead, I’ve picked a simpler table as an
illustrative example, from the very interesting world of the
<a href="https://www.jrf.org.uk/report/minimum-income-standard-britain-what-people-think">‘Minimum Income Standard’</a>.
This is a consensus based measure of how much money is required to live to an acceptable
minimum standard in the UK today. Some of the headline tables are in a more easily
scrapable html page, but the detail is buried in a pdf. And maybe you want that for some
reason? For example, Table 3 in the report gives the amounts that different family types
are judged to need for spending on different things.</p>
<p><img src="mistable.jpg" /></p>
<p><br>
This table is on page 33 of the pdf, so I start by grabbing everything on that page. The
<code>pdf_data()</code> function produces a list with one item per page, so I select the 33rd.</p>
<pre class="r"><code>library(tidyverse)
library(pdftools)
library(knitr)
library(kableExtra)

pdfdata &lt;- pdf_data(&quot;https://www.jrf.org.uk/file/37389/download?token=pg1Xs2Qb&amp;filetype=full-report&quot;) %&gt;% 
  .[[33]]
head(pdfdata)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   width height     x     y space text     
##   &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;    
## 1    52     11   222    42 TRUE  Minimum  
## 2    42     11   277    42 TRUE  income   
## 3    57     11   323    42 TRUE  standards
## 4    15     11   383    42 TRUE  for      
## 5    48     11   402    42 TRUE  selected 
## 6    34     11   454    42 TRUE  family</code></pre>
<p>It grabs every word, one per line of the table, along with its width, height and position
on the page. But how do you make sense of that?? How do you turn this into a table?
The <a href="https://ropensci.org/technotes/2018/12/14/pdftools-20/">blog post</a>
that launched the new feature helpfully says:
“Converting this pdf data into the original data frame is left as an exercise for the
reader :)” with the smiley face and everything, trololol.
So I had to work out a way, which I did, and as ever I’m not convinced it’s the cleverest,
easiest or quickest way…but it’s a way!</p>
<p>To illustrate what the numbers mean in practice, here is how the title of the
table is represented:</p>
<pre class="r"><code>pdfdata[106:115,]</code></pre>
<pre><code>## # A tibble: 10 x 6
##    width height     x     y space text   
##    &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;  
##  1    29     10    72   226 TRUE  Table  
##  2     6     10   104   226 TRUE  3      
##  3    52     10   117   226 TRUE  Summary
##  4    10     10   172   226 TRUE  of     
##  5    17     10   186   226 TRUE  the    
##  6    20     10   207   226 TRUE  MIS    
##  7    15     10   230   226 TRUE  for    
##  8    22     10   249   226 TRUE  four   
##  9    33     10   274   226 TRUE  family 
## 10    30     10   310   226 TRUE  types</code></pre>
<p>All the words have a y co-ordinate of 226, and you can also see how these words
are spread along the x axis from 72 to 340.</p>
<p>I’m not really interested in the title, the first thing I want is the header, which is
on two rows, and I can find out which by searching for the relevant text:</p>
<pre class="r"><code>pdfdata %&gt;% 
  filter(grepl(&quot;Single|Pensioner|Couple|Lone&quot;,text))</code></pre>
<pre><code>## # A tibble: 4 x 6
##   width height     x     y space text     
##   &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;    
## 1    30      9   246   244 FALSE Single   
## 2    48      9   311   244 FALSE Pensioner
## 3    33      9   394   244 FALSE Couple   
## 4    23      9   457   244 TRUE  Lone</code></pre>
<pre class="r"><code>pdfdata %&gt;% 
  filter(grepl(&quot;Commodity|working|couple|children&quot;,text))</code></pre>
<pre><code>## # A tibble: 5 x 6
##   width height     x     y space text     
##   &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;    
## 1    45     11   337   112 TRUE  children,
## 2    38      9   231   256 TRUE  working  
## 3    32      9   319   256 FALSE couple   
## 4    38      9   400   256 FALSE children 
## 5    55      9    72   256 FALSE Commodity</code></pre>
<p>The header is on rows 244 and 256. Where is the bottom of the table?
I don’t want the totals rows, so I only want to go as far as the row with “Rent”.</p>
<pre class="r"><code>pdfdata %&gt;% 
  filter(text == &quot;Rent&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 6
##   width height     x     y space text 
##   &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;
## 1    21      9    72   531 FALSE Rent</code></pre>
<p>This is y = 531. Where are the rows between this?</p>
<pre class="r"><code>pdfdata %&gt;% 
  filter(y &gt; 256 &amp; y &lt; 531) %&gt;% 
  select(y) %&gt;% 
  unique()</code></pre>
<pre><code>## # A tibble: 17 x 1
##        y
##    &lt;int&gt;
##  1   276
##  2   291
##  3   306
##  4   321
##  5   336
##  6   351
##  7   366
##  8   381
##  9   396
## 10   411
## 11   426
## 12   441
## 13   456
## 14   471
## 15   486
## 16   501
## 17   516</code></pre>
<p>17 rows - yup you can see from the table that’s right.
So we know where the rows start and end. What about the columns?
Look for the leftmost word in each:</p>
<pre class="r"><code>pdfdata %&gt;% 
  filter(grepl(&quot;Commodity|working|Pensioner|\\+|Lone&quot;, text)) %&gt;% 
  arrange(x)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   width height     x     y space text     
##   &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;    
## 1    55      9    72   256 FALSE Commodity
## 2    38      9   231   256 TRUE  working  
## 3    48      9   311   244 FALSE Pensioner
## 4     5      9   383   256 TRUE  +        
## 5    23      9   457   244 TRUE  Lone     
## 6     5      9   467   256 TRUE  +</code></pre>
<p>Now we have the numbers the table can be visualised thus (dodgy paint drawings are
not an essential part of this process):</p>
<p><img src="tablelocations.png" /></p>
<p><br>
From here it’s a relatively straightforward merging exercise. I
start by restricting the data I’m working with to within the dimensions of interest, from
the header to the rent expenditure row.</p>
<pre class="r"><code>tabledata &lt;- pdfdata %&gt;% 
  filter(x &gt;= 72) %&gt;% 
  filter(y &gt;= 244 &amp; y &lt;= 531) %&gt;% 
  arrange(x,y)</code></pre>
<p>Mercifully, all the text in each row is on the same y dimension (different sized fonts in different
columns meant that this was not the case in the data I was
dealing with at work!). So each row is represented by a single y value.
But I will need to cut the x values into columns, using the values identified above as
cut points (minus 1 to catch everything). Then it’s just a case of collapsing together
the data within each cell - i.e. each row/column combination - and then a <code>spread()</code>.
Finally the top two rows need to be collapsed together into a single row.</p>
<pre class="r"><code>mistable &lt;- tabledata %&gt;% 
  mutate(col = cut(x, breaks = c(71, 230, 310, 382, 456, Inf), 
                   labels = as.character(c(1:5)))) %&gt;% 
  arrange(col, y) %&gt;% 
  group_by(col, y) %&gt;% 
  mutate(text = paste(text, collapse = &quot; &quot;)) %&gt;% 
  ungroup() %&gt;%
  select(y, text, col) %&gt;% 
  unique() %&gt;% 
  spread(col, text) %&gt;% 
  mutate(row = c(1,1:19)) %&gt;% 
  replace(., is.na(.), &quot;&quot;) %&gt;% 
  group_by(row) %&gt;% 
  summarise_all(paste, collapse = &quot; &quot;) %&gt;%
  mutate_all(., trimws) %&gt;% 
  select(-row, -y)</code></pre>
<p>Nearly there! now just need to make the top row the column names, and
get rid of the penultimate row.</p>
<pre class="r"><code>colnames(mistable) &lt;- mistable[1,]

mistable &lt;- mistable %&gt;% 
  slice(-1) %&gt;% 
  slice(-(nrow(.)-1))

kable(mistable, align = &quot;lcccc&quot;,
      caption = &quot;Components of the Minimum Income Standard for four family types&quot;) %&gt;% 
  kable_styling() %&gt;% 
  footnote(general = &quot;Source: https://www.jrf.org.uk/report/minimum-income-standard-britain-what-people-think&quot;)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Table 1: </span>Components of the Minimum Income Standard for four family types
</caption>
<thead>
<tr>
<th style="text-align:left;">
Commodity
</th>
<th style="text-align:center;">
Single working age
</th>
<th style="text-align:center;">
Pensioner couple
</th>
<th style="text-align:center;">
Couple + 2 children
</th>
<th style="text-align:center;">
Lone parent + 1 child
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Food
</td>
<td style="text-align:center;">
40.34
</td>
<td style="text-align:center;">
53.25
</td>
<td style="text-align:center;">
97.47
</td>
<td style="text-align:center;">
47.05
</td>
</tr>
<tr>
<td style="text-align:left;">
Alcohol
</td>
<td style="text-align:center;">
4.38
</td>
<td style="text-align:center;">
7.40
</td>
<td style="text-align:center;">
6.06
</td>
<td style="text-align:center;">
3.48
</td>
</tr>
<tr>
<td style="text-align:left;">
Tobacco
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Clothing
</td>
<td style="text-align:center;">
7.64
</td>
<td style="text-align:center;">
9.93
</td>
<td style="text-align:center;">
29.26
</td>
<td style="text-align:center;">
16.41
</td>
</tr>
<tr>
<td style="text-align:left;">
Water rates
</td>
<td style="text-align:center;">
4.71
</td>
<td style="text-align:center;">
5.56
</td>
<td style="text-align:center;">
5.45
</td>
<td style="text-align:center;">
7.38
</td>
</tr>
<tr>
<td style="text-align:left;">
Council tax
</td>
<td style="text-align:center;">
13.33
</td>
<td style="text-align:center;">
17.77
</td>
<td style="text-align:center;">
20.73
</td>
<td style="text-align:center;">
15.55
</td>
</tr>
<tr>
<td style="text-align:left;">
Household insurances
</td>
<td style="text-align:center;">
1.79
</td>
<td style="text-align:center;">
1.65
</td>
<td style="text-align:center;">
2.23
</td>
<td style="text-align:center;">
1.99
</td>
</tr>
<tr>
<td style="text-align:left;">
Fuel
</td>
<td style="text-align:center;">
9.00
</td>
<td style="text-align:center;">
10.62
</td>
<td style="text-align:center;">
18.49
</td>
<td style="text-align:center;">
16.43
</td>
</tr>
<tr>
<td style="text-align:left;">
Other housing costs
</td>
<td style="text-align:center;">
2.29
</td>
<td style="text-align:center;">
3.61
</td>
<td style="text-align:center;">
7.26
</td>
<td style="text-align:center;">
2.12
</td>
</tr>
<tr>
<td style="text-align:left;">
Household goods
</td>
<td style="text-align:center;">
9.50
</td>
<td style="text-align:center;">
11.12
</td>
<td style="text-align:center;">
17.39
</td>
<td style="text-align:center;">
16.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Household services
</td>
<td style="text-align:center;">
9.99
</td>
<td style="text-align:center;">
9.07
</td>
<td style="text-align:center;">
13.21
</td>
<td style="text-align:center;">
6.72
</td>
</tr>
<tr>
<td style="text-align:left;">
Childcare
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
186.98
</td>
<td style="text-align:center;">
135.05
</td>
</tr>
<tr>
<td style="text-align:left;">
Personal goods and services
</td>
<td style="text-align:center;">
8.13
</td>
<td style="text-align:center;">
23.65
</td>
<td style="text-align:center;">
27.39
</td>
<td style="text-align:center;">
19.47
</td>
</tr>
<tr>
<td style="text-align:left;">
Motoring
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Other travel costs
</td>
<td style="text-align:center;">
17.03
</td>
<td style="text-align:center;">
4.65
</td>
<td style="text-align:center;">
35.02
</td>
<td style="text-align:center;">
17.16
</td>
</tr>
<tr>
<td style="text-align:left;">
Social and cultural participation
</td>
<td style="text-align:center;">
29.73
</td>
<td style="text-align:center;">
43.21
</td>
<td style="text-align:center;">
90.08
</td>
<td style="text-align:center;">
40.16
</td>
</tr>
<tr>
<td style="text-align:left;">
Rent
</td>
<td style="text-align:center;">
52.30
</td>
<td style="text-align:center;">
64.43
</td>
<td style="text-align:center;">
69.40
</td>
<td style="text-align:center;">
64.07
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup></sup> Source: <a href="https://www.jrf.org.uk/report/minimum-income-standard-britain-what-people-think" class="uri">https://www.jrf.org.uk/report/minimum-income-standard-britain-what-people-think</a>
</td>
</tr>
</tfoot>
</table>
<p>That’s the table! You can admire it, or use the data to make a picture
(after coercing it into a tidy format first).</p>
<pre class="r"><code>mistable %&gt;% 
  filter(Commodity != &quot;Tobacco&quot; &amp; Commodity != &quot;Motoring&quot;) %&gt;% 
  gather(famtype, amount, -Commodity) %&gt;% 
  mutate(amount = as.numeric(amount)) %&gt;% 
  ggplot(aes(famtype, amount, fill = Commodity)) + 
  geom_bar(stat = &quot;identity&quot;, position = &quot;stack&quot;, colour = &quot;black&quot;, size = 0.5) +
  coord_flip() +
  ylab(&quot;Family type&quot;)</code></pre>
<p><img src="/post/2019-03-23-pdf-scraping/index_files/figure-html/finalpic-1.png" width="672" /></p>
<p>You can see the relative size of the total budget and its components for the different family
types (sort of, yeah yeah it’s not the best viz in the world, I’ve run out of steam after
all that pdf wrangling.) Look at the size of the childcare component (shown here in orange)!</p>
